#!/usr/bin/env python3
"""Independent BLE preamble-localization primitives.

This module is intentionally local to PhantomChannel.  It does not import the
PhantomChannel receiver parser and it never consults payload, CRC, RTT, or an
existing parser row while choosing a correlation peak.

Provenance: independent local reconstruction for the 2026-08-09 experiment;
no external parser source is imported or monkey-patched.  The protected
PhantomChannel receiver dependency was recorded at Git HEAD
b973d3c75e38fa3d3f8292424126e83bf31e8065 during the experiment.

The implementation is a compact reference BPL path for the offline ablation:
BLE preamble bits are converted to a Gaussian-filtered GFSK template, a small
CFO bank is searched, and the normalized complex correlation produces the
start/quality metrics required by the failure funnel.
"""

from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Any, Iterable, Sequence

import numpy as np
from scipy.signal import find_peaks


@dataclass(frozen=True)
class BPLConfig:
    phy: str = "LE_1M"
    sample_rate_sps: float = 4_000_000.0
    symbol_rate_sps: float = 1_000_000.0
    gaussian_bt: float = 0.5
    gaussian_span_symbols: int = 4
    template_mode: str = "preamble"
    min_normalized_peak: float = 0.20
    min_peak_ratio: float = 1.05
    max_peak_width_samples: int = 64
    competing_peak_relative_threshold: float = 0.80
    peak_guard_samples: int = 12
    search_guard_samples: int = 16
    search_tail_samples: int = 512
    cfo_search_hz: tuple[float, ...] = (-100_000.0, -50_000.0, 0.0, 50_000.0, 100_000.0)

    @property
    def samples_per_symbol(self) -> int:
        value = self.sample_rate_sps / self.symbol_rate_sps
        rounded = int(round(value))
        if rounded < 1 or abs(value - rounded) > 1e-6:
            raise ValueError("sample_rate_sps/symbol_rate_sps must be a positive integer")
        return rounded

    @property
    def preamble_bits_count(self) -> int:
        normalized = self.phy.upper().replace("-", "_")
        if normalized in {"LE_1M", "1M", "1M_PHY"}:
            return 8
        if normalized in {"LE_2M", "2M", "2M_PHY"}:
            return 16
        raise ValueError(f"unsupported PHY: {self.phy}")

    def as_dict(self) -> dict[str, Any]:
        result = asdict(self)
        result["cfo_search_hz"] = list(self.cfo_search_hz)
        result["samples_per_symbol"] = self.samples_per_symbol
        result["preamble_bits_count"] = self.preamble_bits_count
        return result


def _normalize_bits(bits: Iterable[int]) -> list[int]:
    result = [int(bit) & 1 for bit in bits]
    if not result:
        raise ValueError("at least one bit is required")
    return result


def ble_preamble_bits(
    phy: str,
    *,
    access_address: int | None = None,
    polarity: int | None = None,
) -> list[int]:
    """Return a legal BLE preamble hypothesis in on-air bit order.

    With no AA supplied both legal polarities are generated by
    :func:`build_templates`.  The exact AA bit order is kept out of the BPL
    selection path when the AA is unknown; the two hypotheses only encode the
    two possible preamble polarities.
    """

    config = BPLConfig(phy=phy)
    if polarity is None:
        if access_address is None:
            raise ValueError("polarity or access_address is required")
        polarity = (int(access_address) & 1) ^ 1
    value = int(polarity) & 1
    return [value] * config.preamble_bits_count


def _gaussian_kernel(samples_per_symbol: int, bt: float, span_symbols: int) -> np.ndarray:
    if bt <= 0 or span_symbols < 1:
        raise ValueError("invalid Gaussian filter parameters")
    length = max(3, int(span_symbols * samples_per_symbol) | 1)
    time = np.arange(length, dtype=np.float64) - (length - 1) / 2.0
    # A normalized Gaussian approximation is sufficient for the reference
    # template, provided generation and synthetic tests use the same formula.
    sigma = samples_per_symbol * np.sqrt(np.log(2.0)) / (2.0 * np.pi * bt)
    kernel = np.exp(-0.5 * (time / sigma) ** 2)
    return kernel / np.sum(kernel)


def generate_gfsk_template(bits: Sequence[int], config: BPLConfig) -> np.ndarray:
    """Generate a unit-power complex GFSK template from BLE on-air bits."""

    normalized_bits = _normalize_bits(bits)
    sps = config.samples_per_symbol
    nrz = np.repeat(2.0 * np.asarray(normalized_bits, dtype=np.float64) - 1.0, sps)
    shaped = np.convolve(
        nrz,
        _gaussian_kernel(sps, config.gaussian_bt, config.gaussian_span_symbols),
        mode="same",
    )
    phase_increment = np.pi * 0.5 * shaped / float(sps)
    phase = np.cumsum(phase_increment)
    template = np.exp(1j * phase).astype(np.complex64)
    power = float(np.mean(np.abs(template) ** 2))
    return template / np.sqrt(max(power, 1e-12))


def build_templates(
    config: BPLConfig,
    *,
    candidate_access_addresses: Sequence[int] | None = None,
) -> list[tuple[str, np.ndarray]]:
    """Build pure-preamble or explicitly named preamble+AA hypotheses."""

    aa_values = list(candidate_access_addresses or [])
    hypotheses: list[tuple[str, list[int]]] = []
    if aa_values:
        for aa in aa_values:
            first_bit = int(aa) & 1
            preamble = ble_preamble_bits(config.phy, polarity=first_bit ^ 1)
            bits = preamble
            if config.template_mode == "preamble+aa":
                aa_bits = [(int(aa) >> index) & 1 for index in range(32)]
                bits = preamble + aa_bits
            hypotheses.append((f"aa_{int(aa) & 0xFFFFFFFF:08X}", bits))
    else:
        for polarity in (0, 1):
            bits = ble_preamble_bits(config.phy, polarity=polarity)
            hypotheses.append((f"preamble_polarity_{polarity}", bits))
    return [(template_id, generate_gfsk_template(bits, config)) for template_id, bits in hypotheses]


def _normalized_correlation(signal: np.ndarray, template: np.ndarray) -> np.ndarray:
    signal = np.asarray(signal, dtype=np.complex64).reshape(-1)
    template = np.asarray(template, dtype=np.complex64).reshape(-1)
    if signal.size < template.size:
        return np.empty(0, dtype=np.complex64)
    correlation = np.convolve(signal, np.conj(template[::-1]), mode="valid")
    signal_power = np.convolve(np.abs(signal) ** 2, np.ones(template.size), mode="valid")
    template_power = float(np.sum(np.abs(template) ** 2))
    denominator = np.sqrt(np.maximum(signal_power * template_power, 1e-12))
    return (correlation / denominator).astype(np.complex64)


def _parabolic_offset(values: np.ndarray, index: int) -> float:
    if index <= 0 or index + 1 >= values.size:
        return 0.0
    left, center, right = [float(values[index + delta]) for delta in (-1, 0, 1)]
    denominator = left - 2.0 * center + right
    if abs(denominator) < 1e-12:
        return 0.0
    return float(np.clip(0.5 * (left - right) / denominator, -0.5, 0.5))


def _peak_metrics(magnitude: np.ndarray, config: BPLConfig) -> dict[str, Any]:
    if magnitude.size == 0:
        return {
            "peak_index": None,
            "normalized_peak": 0.0,
            "second_peak": 0.0,
            "peak_to_second_ratio": 0.0,
            "peak_width_samples": 0,
            "competing_peak_count": 0,
            "fractional_offset": 0.0,
            "failure_code": "B4_START_OUT_OF_RANGE",
        }
    peak_index = int(np.argmax(magnitude))
    peak_value = float(magnitude[peak_index])
    guard = max(1, int(config.peak_guard_samples))
    available = magnitude.copy()
    left = max(0, peak_index - guard)
    right = min(available.size, peak_index + guard + 1)
    available[left:right] = 0.0
    second_value = float(np.max(available)) if np.any(available) else 0.0
    ratio = peak_value / max(second_value, 1e-12)
    half = peak_value * 0.5
    first = peak_index
    last = peak_index
    while first > 0 and magnitude[first - 1] >= half:
        first -= 1
    while last + 1 < magnitude.size and magnitude[last + 1] >= half:
        last += 1
    width = int(last - first + 1)
    peaks, _ = find_peaks(
        magnitude,
        height=peak_value * float(config.competing_peak_relative_threshold),
        distance=max(1, guard),
    )
    competing = int(sum(1 for item in peaks if abs(int(item) - peak_index) > guard))
    fractional = _parabolic_offset(magnitude, peak_index)
    if peak_value < config.min_normalized_peak:
        failure = "B1_LOW_CORRELATION"
    elif ratio < config.min_peak_ratio:
        failure = "B2_AMBIGUOUS_PEAKS"
    elif width > config.max_peak_width_samples:
        failure = "B3_BROAD_PEAK"
    else:
        failure = "PASS"
    return {
        "peak_index": peak_index,
        "normalized_peak": peak_value,
        "second_peak": second_value,
        "peak_to_second_ratio": ratio,
        "peak_width_samples": width,
        "competing_peak_count": competing,
        "fractional_offset": fractional,
        "failure_code": failure,
    }


def localize_preamble(
    complex_iq: np.ndarray,
    config: BPLConfig,
    *,
    candidate_access_addresses: Sequence[int] | None = None,
    search_start_sample: int | None = None,
    search_end_sample: int | None = None,
) -> dict[str, Any]:
    """Run BPL and return an auditable scalar result dictionary.

    ``search_end_sample`` is exclusive.  Bounds are applied before the
    correlation, so samples outside the declared candidate search interval
    cannot win the peak selection.  The returned indices remain in the input
    signal's coordinate system.
    """

    signal = np.asarray(complex_iq, dtype=np.complex64).reshape(-1)
    search_start = max(0, int(search_start_sample)) if search_start_sample is not None else 0
    search_end = min(signal.size, int(search_end_sample)) if search_end_sample is not None else signal.size
    if search_end < search_start:
        search_end = search_start
    search_signal = signal[search_start:search_end]
    templates = build_templates(config, candidate_access_addresses=candidate_access_addresses)
    best: dict[str, Any] | None = None
    best_correlation: complex = 0j
    for template_id, template in templates:
        for cfo_hz in config.cfo_search_hz:
            index = np.arange(search_signal.size, dtype=np.float32)
            rotated = search_signal * np.exp(-2j * np.pi * float(cfo_hz) * index / config.sample_rate_sps)
            correlation = _normalized_correlation(rotated, template)
            metrics = _peak_metrics(np.abs(correlation), config)
            if best is None or float(metrics["normalized_peak"]) > float(best["normalized_peak"]):
                local_peak = metrics.get("peak_index")
                best = dict(metrics)
                if local_peak is not None:
                    best["peak_index"] = int(local_peak) + search_start
                    best_correlation = correlation[int(local_peak)]
                else:
                    best_correlation = 0j
                best.update({"template_id": template_id, "coarse_cfo_hz": float(cfo_hz)})
    if best is None:
        best = _peak_metrics(np.empty(0), config)
        best.update({"template_id": "", "coarse_cfo_hz": 0.0})
    peak_index = best.get("peak_index")
    fractional = float(best.get("fractional_offset", 0.0) or 0.0)
    packet_start = None if peak_index is None else float(peak_index) + fractional
    preamble_end = None if packet_start is None else packet_start + config.preamble_bits_count * config.samples_per_symbol
    best.update(
        {
            "accepted": bool(best["failure_code"] == "PASS"),
            "packet_start_sample": packet_start,
            "preamble_end_sample": preamble_end,
            "phase_at_peak_rad": float(np.angle(best_correlation)),
            "config_phy": config.phy,
            "template_mode": config.template_mode,
            "search_start_sample": search_start,
            "search_end_sample": search_end,
        }
    )
    return best


def config_from_mapping(mapping: dict[str, Any]) -> BPLConfig:
    values = dict(mapping)
    if "cfo_search_hz" in values:
        values["cfo_search_hz"] = tuple(float(item) for item in values["cfo_search_hz"])
    return BPLConfig(**values)
